### ISSUE TITLE
Attempted to read or write protected memory.

### ISSUE THREAD

**Issue by 1rosehip** [SWI-Prolog/contrib-swiplcs#1]
Hello,
Thank you for the useful library.
I try to run "HelloWorldDemo" example from documentation and get the following error:

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.WriteInt64(IntPtr ptr, Int32 ofs, Int64 val)
   at System.Runtime.InteropServices.Marshal.WriteIntPtr(IntPtr ptr, IntPtr val)
   at SbsSW.SwiPlCs.libpl.SetStreamFunction(PlStreamType streamType, StreamsFunction functionType, Delegate function)
   at SbsSW.SwiPlCs.PlEngine.Initialize(String[] argv)

I use Visual Sudio 2010

Do you have any ideas?

Thank you

**Comment by hiiamjack99** [comment]
> Xin chào Miriam,
> 
> Không có gì.
> Nếu 'HelloWorldDemo' không hoạt động, nó có thể là phiên bản không khớp.
> 
> Hãy trả lời những câu hỏi sau đây:
> 
> 1. Bạn sử dụng phiên bản SWI-Prolog nào? 
>    (truy vấn cho? - phiên bản. (số và phiên bản 32 hoặc 64 bit))
> 2. Bạn biên dịch phiên bản khung .net nào? 
>    (cả số phiên bản và 32 hoặc 64 bit)
> 3. bạn sử dụng phiên bản SwiPlCs.dll nào? 
>    Hay bạn đã biên dịch nó từ các nguồn? Nếu có với những thuộc tính nào? 
>    (bạn có thể xác định phiên bản của SwiPlCs.dll nếu bạn nhấp chuột phải vào tệp - thuộc tính - chi tiết - Fileversion hoặc Productversion)
> 
> Với thông tin trên, tôi có thể giúp bạn chạy nó.
> 
> Uwe
> 
> > ----- Tin nhắn gốc ----- 
> > Từ: Miriam Zusin [mailto: [notification@github.com](mailto:notifications@github.com) ] 
> > Đã gửi: Thứ Ba, ngày 05 tháng 8 năm 2014 10:31 SA 
> > Tới: SWI-Prolog / Contrib-swiplcs 
> > Chủ đề: [đóng góp -swiplcs] Đã cố đọc hoặc ghi bộ nhớ được bảo vệ. 
> > ( [# 1](https://github.com/SWI-Prolog/contrib-swiplcs/issues/1) )
> > Xin chào, 
> > Cảm ơn bạn đã có thư viện hữu ích. 
> > Tôi cố gắng chạy ví dụ "HelloWorldDemo" từ tài liệu và gặp 
> > lỗi sau:
> > Ngoại lệ không được xử lý: System.AccessViolationException: Đã cố gắng đọc 
> > hoặc ghi bộ nhớ được bảo vệ. Đây thường là dấu hiệu cho thấy 
> > bộ nhớ khác bị hỏng. 
> > tại System.Runtime.InteropServices.Marshal.WriteInt64 (IntPtr ptr, Int32 
> > ofs, Int64 val) 
> > tại System.Runtime.InteropServices.Marshal.WriteIntPtr (IntPtr ptr, 
> > IntPtr val) 
> > tại SbsSW.SwiPlCStunctions.libpl.SetStreamF Streams, 
> > Plunctions. functionType, Delegate function) 
> > tại SbsSW.SwiPlCs.PlEngine.Initialize (String [] argv)
> > Tôi sử dụng Visual Sudio 2010
> > Bạn có bất cứ ý tưởng?
> > Cảm ơn bạn
> > - 
> > Trả lời email này trực tiếp hoặc xem nó trên GitHub 
> > [# 1](https://github.com/SWI-Prolog/contrib-swiplcs/issues/1) . 
> > < [Https://github.com/notifications/beacon/7372553__eyJzY29wZSI6Ik5ld3NpZ](https://github.com/notifications/beacon/7372553__eyJzY29wZSI6Ik5ld3NpZ) 
> > XM6QmVhY29uIiwiZXhwaXJlcyI6MTcyMjg0NjY4NCwiZGF0YSI6eyJpZCI6Mzg4MjQ5NzZ9 
> > fq == - 3db03d741e8468433fd7418bd4e97eb712b1eba2.gif>

Thanks very much. I love U <3

**Comment by rjsargeant** [comment]
I am trying to set up the swiPlCs interface but I have been unable to resolve a persistent System.AccessViolationException.  I am using the latest version 60605 version.  I have included the swi-prolog bin directory in the path variable.  The sample program is reading the  swiPLCs DLL as demonstrated in intellisense.  I am using the 64 bit dll, 64 bit swi-prolog, and .Net 5.  I have tried the other various fixes such as renaming the 64 bit dll and adding the SWI_HOME_DIR variable.  I have tried earlier versions of the swiPICs but  with the same error.  Any thoughts would be appreciated.

**Comment by JanWielemaker** [comment]
Not sure, but you may have to recompile the C# binding.   The SWI-Prolog API is often not binary compatible between major versions.   It is usually source code compatible.    Another possible issue is that SWI-Prolog precompiled binaries are compiled with MinGW64 (GCC for Windows) rather than VS.    I'm not sure about the compatibility (any Windows gurus?)  Otherwise I guess you need a debugger.
